src/block/node/CodeNode.ts, src/block/node/DecorationNode.ts, src/block/node/HashTagNode.ts, src/block/node/IconNode.ts, src/block/node/InternalLinkNode.ts, src/block/node/PlainNode.ts, src/block/node/QuoteNode.ts, src/block/node/StrongNode.ts, src/block/node/UrlNode/index.ts, src/block/node/index.ts
[src/block/node/index.ts from progfay/scrapbox-parser - Code Climate](https://codeclimate.com/github/progfay/scrapbox-parser/src/block/node/index.ts/source#issue-7a57b4460776c5e102554eab09f6b660)
=> Split and combine NodeParser

src/block/node/HashTagNode.ts, tests/line/hashTag.test.ts
- fix parsing of multiple hashTag ( #3 )
=> fix: support multiple hashTag parsing

src/block/node/UrlNode/index.ts, tests/line/link.test.ts
=> Fix [link link]

package.json
Thank you very much for your wonderful project!
- Change `"license": "ISC"` => `"license": "MIT"` in `package.json`
=> chore: change license in package.json to MIT

jest.config.js, package-lock.json, tests/codeBlock/index.test.ts, tests/jest-setup.ts, tests/line/blank.test.ts, tests/line/bullet.test.ts, tests/line/code.test.ts, tests/line/decoration.test.ts, tests/line/formula.test.ts, tests/line/googleMap.test.ts, tests/line/hashTag.test.ts, tests/line/helpfeel.test.ts, tests/line/icon.test.ts, tests/line/image.test.ts, tests/line/index.test.ts, tests/line/link.test.ts, tests/line/plain.test.ts, tests/line/quote.test.ts, tests/line/strong.test.ts, tests/line/strongIcon.test.ts, tests/line/strongImage.test.ts, tests/table/index.test.ts
- use Custom matcher ( `toEqualWhenParsing` ) with jest
=> Test(jest): use custom matcher

src/block/BlockComponent.ts, src/index.ts, src/stream/CombinedStream.ts, src/stream/ConvertToBlockStream.ts, src/stream/PackingBlockStream.ts, src/stream/ParsingStream.ts, src/stream/index.ts, tests/stream/body.txt, tests/stream/index.test.ts
=> Feat: Scrapbox parser with Streaming API

tests/jest-setup.ts, tests/line/decoration.test.ts, tests/stream/index.test.ts, tests/table/index.test.ts, tests/title/index.test.ts
- Unify endpoint of API used by `/tests`
=> Refactor(test): import from `/src/index.ts`

.gitignore, package-lock.json, package.json, tsconfig.umd.json, webpack.config.js
```sh
$ npm run build:umd
```
And output to `/umd` directory
=> Feat: build to UMD module type

.eslintignore, .travis.yml, package.json, tsconfig.eslint.json
- Run `npm run lint` before `npm test` on Travis CI
=> Chore: lint code on Travis CI

package-lock.json
=> Chore: Security update 2020/03/18

.travis.yml, README.md, package-lock.json, package.json
- Remove coverage checking with Coveralls
=> Chore(coveralls): remove coverage checking

.eslintrc.js, src/block/PackedBlockComponent.ts
- Enable `@typescript-eslint/consistent-type-assertions`
=> Style(@typescript-eslint): enable consistent-type-assertions rule

.eslintrc.js, src/block/PackedBlockComponent.ts, src/block/node/FormulaNode.ts, src/block/node/GoogleMapNode.ts, src/block/node/StrongImageNode.ts, src/block/node/UrlNode/index.ts
- Enable `@typescript-eslint/prefer-nullish-coalescing`
=> Style(typescript-eslint): enable prefer-nullish-coalescing

.eslintrc.js, src/block/node/GoogleMapNode.ts, src/block/node/StrongImageNode.ts, src/block/node/UrlNode/index.ts
- Enable `@typescript-eslint/prefer-optional-chain`
=> Style(typescript-eslint): enable prefer-optional-chain

.eslintrc.js, src/block/PackedBlockComponent.ts, src/block/node/BlankNode.ts, src/block/node/CodeNode.ts, src/block/node/DecorationNode.ts, src/block/node/FormulaNode.ts, src/block/node/GoogleMapNode.ts, src/block/node/HashTagNode.ts, src/block/node/HelpfeelNode.ts, src/block/node/IconNode.ts, src/block/node/InternalLinkNode.ts, src/block/node/QuoteNode.ts, src/block/node/StrongIconNode.ts, src/block/node/StrongImageNode.ts, src/block/node/StrongNode.ts, src/block/node/UrlNode/index.ts, src/block/node/index.ts, src/parse.ts
- Enable `@typescript-eslint/strict-boolean-expressions`
=> Style(typescript-eslint): enable /strict-boolean-expressions

src/block/node/IconNode.ts, src/block/node/StrongIconNode.ts, tests/line/__snapshots__/icon.test.ts.snap, tests/line/__snapshots__/strongIcon.test.ts.snap, tests/line/icon.test.ts, tests/line/strongIcon.test.ts
- Fix parsing when internal link and icon are on same line (#212)
=> Fix(icon): fix parsing when internal link and icon are on same line

src/block/PackedBlockComponent.ts
- Refactoring `packBlockComponents` function to improve cognitive complexity
- issue of Code Climate: https://codeclimate.com/github/progfay/scrapbox-parser/src/block/PackedBlockComponent.ts/source#issue-91931f962d62f266bee1e823161393c4
=> Refactor: improve cognitive complexity of packBlockComponents

.travis.yml
- Reference: https://docs.codeclimate.com/docs/travis-ci-test-coverage
[![Test Coverage](https://img.shields.io/codeclimate/coverage/progfay/scrapbox-parser?style=for-the-badge&message=Code+Climate&labelColor=000000&logo=Code+Climate&logoColor=FFFFFF)](https://codeclimate.com/github/progfay/scrapbox-parser/test_coverage)
=> Chore: send test coverage from Travis CI to Code Climate

README.md
- Add budge for README.md
[![Test Coverage](https://img.shields.io/codeclimate/coverage/progfay/scrapbox-parser?style=for-the-badge&message=Code+Climate&labelColor=222222&logo=Code+Climate&logoColor=FFFFFF)](https://codeclimate.com/github/progfay/scrapbox-parser/coverage)
=> doc: add Budge of Test Coverage

.eslintrc.js, .prettierrc, README.md, package-lock.json, src/block/PackedBlockComponent.ts, src/block/index.ts, src/block/node/UrlNode/index.ts, tests/jest-setup.ts, tests/line/icon.test.ts, tests/line/strongIcon.test.ts
- Ref. https://blog.ojisan.io/eslint-prettier
=> Style(prettier): set config

.prettierrc, src/block/CodeBlock.ts, src/block/PackedBlockComponent.ts, src/block/Table.ts, src/block/Title.ts, src/block/index.ts, src/block/node/DecorationNode.ts, src/block/node/FormulaNode.ts, src/block/node/GoogleMapNode.ts, src/block/node/HashTagNode.ts, src/block/node/HelpfeelNode.ts, src/block/node/IconNode.ts, src/block/node/InternalLinkNode.ts, src/block/node/StrongIconNode.ts, src/block/node/StrongImageNode.ts, src/block/node/StrongNode.ts, src/block/node/UrlNode/ExternalLinkNode.ts, src/block/node/UrlNode/index.ts, src/block/node/index.ts, src/parse.ts, tests/jest-setup.ts, tests/line/image.test.ts, tests/line/link.test.ts, tests/line/strongImage.test.ts, tsconfig.json
- To resolve #257 #258 #259 #260 #261 #262
=> Style(prettier): change printWidth

src/block/node/GoogleMapNode.ts
- To resolve #272,
- Split process of parsing coordinate
- Use `RegExp`
=> Refactor: reduce cognitive complexity

src/block/node/CodeNode.ts, src/block/node/CommandLineNode.ts, src/block/node/index.ts, tests/line/__snapshots__/code.test.ts.snap, tests/line/__snapshots__/commandLine.test.ts.snap, tests/line/code.test.ts, tests/line/commandLine.test.ts
- Separate command notation to CommandLineNode from CodeNode
- Support `% command` notation
=> Feat: impl CommandLineNode

src/block/node/IconNode.ts, src/block/node/StrongIconNode.ts
- To resolve #273 , resolve #274
=> Refactor: extract process of parsing IconNode and StrongIconNode

src/block/Line.ts, src/block/Table.ts, src/block/node/BlankNode.ts, src/block/node/CodeNode.ts, src/block/node/CommandLineNode.ts, src/block/node/DecorationNode.ts, src/block/node/ExternalLinkNode.ts, src/block/node/FormulaNode.ts, src/block/node/GoogleMapNode.ts, src/block/node/HashTagNode.ts, src/block/node/HelpfeelNode.ts, src/block/node/IconNode.ts, src/block/node/ImageNode.ts, src/block/node/InternalLinkNode.ts, src/block/node/PlainNode.ts, src/block/node/QuoteNode.ts, src/block/node/StrongIconNode.ts, src/block/node/StrongImageNode.ts, src/block/node/StrongNode.ts, src/block/node/creator.ts, src/block/node/index.ts, src/block/node/type.ts, src/index.ts
- Rename `LineNode` to `Node`
- Merge `ExternalLinkNode` and `InternalLinkNode` to `LinkNode`
=> Refactor: rename node types

src/block/node/IconNode.ts, src/block/node/StrongIconNode.ts
- Use [Overloads](https://www.typescriptlang.org/docs/handbook/functions.html#overloads) of TypeScript
=> Feat(generateIconNodeCreator): overload type of function

.github/workflows/codeql-analysis.yml
- Add CodeQL for this repository
=> Chore: create codeql-analysis.yml

src/index.ts
- Export `CommandLineNode` type
=> fix(CommandLineNode): export type

src/block/BlockComponent.ts
=> Refactor: merge convertToBlockComponent

src/block/BlockComponent.ts, src/parse.ts
=> refactor: rename convertToBlockComponents to parseToBlockComponents

src/block/PackedBlockComponent.ts, src/parse.ts, tests/jest-setup.ts
- Make `ParserOption` interface partially
- Optional property: `ParserOption['hasTitle']`
=> Feat(type): make ParserOption interface partially

src/block/PackedBlockComponent.ts
- Extract `callbackFn` (first argument of `Array.prototype.reduce` ) in `packBlockComponents`
- To resolve #396
=> refactor(packBlockComponents): extract callbackFn of Array.reduce

src/block/Pack.ts
- Reduce unnecessary matching of `RegExp`
=> Refactor(RegExp): remove unnecessary trailing match

.cspell.json, .vscode/settings.json, package-lock.json, package.json, src/block/node/ImageNode.ts
- Add spell checker, [cspell](https://www.npmjs.com/package/cspell)
- Add dictionary for cspell
- Support VSCode extension [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
=> Chore(cspell): add spell check linter

src/block/node/ExternalLinkNode.ts
- Avoid inefficient regular expression on matching `ExternalLinkNode` .
=> Fix(ExternalLinkNode): fix Inefficient regular expression

.prettierignore, tsconfig.json
- Migrate to newer tsconfig
- Ref. https://gist.github.com/azu/56a0411d69e2fc333d545bfe57933d07
=> Chore(tsc): update tsconfig.json

src/block/CodeBlock.ts, src/block/Pack.ts, src/block/Row.ts, src/block/Table.ts, src/block/node/CommandLineNode.ts, src/block/node/ExternalLinkNode.ts, src/block/node/GoogleMapNode.ts, src/block/node/creator.ts, src/parse.ts, tests/line/icon.test.ts, tests/line/strongIcon.test.ts, tsconfig.json
- Enable [`noUncheckedIndexedAccess`](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1-beta/#no-unchecked-indexed-access) options
=> Feat(TypeScript): enable noUncheckedIndexedAccess

package.json
- Lint with Prettier on `npm run lint`
=> Chore(npm-script): add prettier for linting

src/parse.ts
- Simply RegExp for title matching.
- In this case, no risk for ReDoS.
=> Refactor: improve efficiency of title matching

src/block/node/HashTagNode.ts, tests/line/__snapshots__/hashTag.test.ts.snap
- For compatibility with Safari
- Ref. #667
=> Feat: no-use lookbehind RegExp

src/block/node/BlankNode.ts, src/block/node/CodeNode.ts, src/block/node/CommandLineNode.ts, src/block/node/DecorationNode.ts, src/block/node/ExternalLinkNode.ts, src/block/node/FormulaNode.ts, src/block/node/GoogleMapNode.ts, src/block/node/HashTagNode.ts, src/block/node/HelpfeelNode.ts, src/block/node/IconNode.ts, src/block/node/ImageNode.ts, src/block/node/InternalLinkNode.ts, src/block/node/PlainNode.ts, src/block/node/QuoteNode.ts, src/block/node/StrongIconNode.ts, src/block/node/StrongImageNode.ts, src/block/node/StrongNode.ts, src/block/node/creator.ts
- Export the option of `createNodeParser` of each node
- Preparation for https://github.com/progfay/scrapbox-parser/issues/869
=> export options of createNodeParser

src/block/node/HashTagNode.ts, tests/line/__snapshots__/decoration.test.ts.snap, tests/line/decoration.test.ts, tests/table/__snapshots__/index.test.ts.snap, tests/table/index.test.ts
https://github.com/progfay/scrapbox-parser/issues/867
-
=> Parse hashTag on nested nodes

src/block/Line.ts, src/block/Table.ts, src/block/node/BlankNode.ts, src/block/node/CodeNode.ts, src/block/node/CommandLineNode.ts, src/block/node/DecorationNode.ts, src/block/node/ExternalLinkNode.ts, src/block/node/FormulaNode.ts, src/block/node/GoogleMapNode.ts, src/block/node/HashTagNode.ts, src/block/node/HelpfeelNode.ts, src/block/node/IconNode.ts, src/block/node/ImageNode.ts, src/block/node/InternalLinkNode.ts, src/block/node/PlainNode.ts, src/block/node/QuoteNode.ts, src/block/node/StrongImageNode.ts, src/block/node/StrongNode.ts, src/block/node/creator.ts, src/block/node/index.ts, tests/table/__snapshots__/index.test.ts.snap, tests/table/index.test.ts
- ref. https://github.com/progfay/scrapbox-parser/issues/869
- Fix behavior for parsing table cells
=> Fix table cell parsing

package-lock.json, package.json
- Run `npm exec npm-check-updates -u && npm install`
=> chore(package): upgrade @types/node to 17.0.2

src/block/node/IconNode.ts, tests/line/__snapshots__/decoration.test.ts.snap, tests/line/decoration.test.ts
=> Fix decoration with icons

jsr.json
- ref. https://jsr.io/@progfay/scrapbox-parser/publish
=> chore: add `jsr.json`

src/block/node/BlankNode.ts, src/block/node/CodeNode.ts, src/block/node/CommandLineNode.ts, src/block/node/DecorationNode.ts, src/block/node/ExternalLinkNode.ts, src/block/node/NumberListNode.ts, src/block/node/PlainNode.ts, src/block/node/QuoteNode.ts, src/block/node/StrongNode.ts, src/block/node/creator.ts, src/block/node/index.ts
=> prepare for publishing to JSR

README.md, src/block/CodeBlock.ts, src/block/Line.ts, src/block/Row.ts, src/block/Table.ts, src/block/Title.ts, src/block/index.ts, src/block/node/DecorationNode.ts, src/block/node/type.ts, src/parse.ts
- https://jsr.io/docs/writing-docs#symbol-documentation
=> add documents for JSR

src/block/Row.ts, src/index.ts
=> refactor: remove some unused exports

.cspell.json, .vscode/extensions.json, .vscode/settings.json, package-lock.json, package.json
- use [`streetsidesoftware.code-spell-checker`](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) VSCode Extension instead of [`cspell`](https://www.npmjs.com/package/cspell) package
=> remove cspell

package-lock.json, package.json
=> re-install `npm-run-all2` package

src/block/node/ImageNode.ts
=> `npm run format`

vite.config.ts
- ref. https://nodejs.org/en/learn/modules/publishing-a-package
=> publish only-ESM code

package-lock.json, package.json
=> remove `npm-run-all2`

docs/index.html, docs/script.js, package.json
=> add `/docs`

.github/workflows/create-release-pr.yml
=> change release note template temporarily

.github/workflows/create-release-pr.yml
Reverts progfay/scrapbox-parser#1924
=> Revert "change release note template temporarily"
