- jest.config.js
- tests/codeBlock/index.test.ts
- tests/line/blank.test.ts
- tests/line/bullet.test.ts
- tests/line/code.test.ts
- tests/line/decoration.test.ts
- tests/line/formula.test.ts
- tests/line/googleMap.test.ts
- tests/line/hashTag.test.ts
- tests/line/helpfeel.test.ts
- tests/line/icon.test.ts
- tests/line/image.test.ts
- tests/line/index.test.ts
- tests/line/link.test.ts
- tests/line/plain.test.ts
- tests/line/quote.test.ts
- tests/line/strong.test.ts
- tests/line/strongIcon.test.ts
- tests/line/strongImage.test.ts
- tests/table/index.test.ts
- Use [`setupFilesAfterEnv`](https://jestjs.io/docs/en/configuration.html#setupfilesafterenv-array)
- Remove `import '../../jest-setup'` from test files
> Refactor(test): use `setupFilesAfterEnv` of jest

- src/block/node/UrlNode/index.ts
- tests/line/image.test.ts
- tests/line/link.test.ts
- Parse image link with GET parameters
- e.g. http://example.com/image.png?key1=value1&key2=value2
> Feat: parse image link with GET parameters

- src/index.ts
- src/parse.ts
- tests/title/index.test.ts
- Add `getTitle` function
- High performance when parsing huge page
> Feat: add function to get title of page

- src/stream/index.ts
- tests/jest-setup.ts
- tests/page/__snapshots__/index.test.ts.snap
- tests/page/index.test.ts
- tests/stream/index.test.ts
- Add test case to `parse` , `ScrapboxParserStream`
- Without 2nd argument `option` (optional)
> Test: add case for calling API without option

- src/block/node/BlankNode.ts
- src/block/node/CodeNode.ts
- src/block/node/DecorationNode.ts
- src/block/node/FormulaNode.ts
- src/block/node/GoogleMapNode.ts
- src/block/node/HashTagNode.ts
- src/block/node/HelpfeelNode.ts
- src/block/node/IconNode.ts
- src/block/node/InternalLinkNode.ts
- src/block/node/QuoteNode.ts
- src/block/node/StrongIconNode.ts
- src/block/node/StrongImageNode.ts
- src/block/node/StrongNode.ts
- src/block/node/UrlNode/index.ts
- src/block/node/index.ts
- In development, `ParserOptionType` is conflict.
- `/src/parse.ts` (global parser)
- `/src/block/node/index.ts` (internal node parser)
- To resolve the conflict, rename internal node parser types
> Refactor(types): Rename internal node parser types

- .gitignore
- tsconfig.cjs.json
- tsconfig.esm.json
- tsconfig.json
- tsconfig.umd.json
- Set `tsBuildInfoFile` option to tsconfig files for building.
```sh
npm run build  22.46s user 2.13s system 124% cpu 19.777 total
```
```sh
npm run build  11.41s user 1.17s system 138% cpu 9.085 total
```
> Feat(tsconfig): set `tsBuildInfoFile` options

- src/block/node/index.ts
- Before: To run `convertToLineNodes`, `parser.slice().reverse()` is executed.
- After: `parser.slice().reverse()` is executed only once. (On initialize `convertToLineNodes`)
> Refactor(combineNodeParsers): reverse node parsers only once

- src/block/node/index.ts
- Use [`array.reduceRight`](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/reduceRight) instead of [`array.reduce`](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce) in `combineNodeParsers` .
> Refactor(combineNodeParsers): use array.reduceRight

- package-lock.json
- Resolve Security Alert, [CVE-2020-7598](https://github.com/advisories/GHSA-vh95-rmgr-6w4m).
> chore: $ npm audit fix

- .eslintrc.js
- package-lock.json
- package.json
- Install and setup [`eslint-config-standard-with-typescript`](https://www.npmjs.com/package/eslint-config-standard-with-typescript) .
- Disable the rule that caused error in the current code.
> Chore: use standard-with-typescript for lint

- .eslintrc.js
- src/block/node/InternalLinkNode.ts
- src/block/node/index.ts
- tests/jest-setup.ts
- Enable rules of `standard-with-typescript`
- `@typescript-eslint/indent`
- `@typescript-eslint/method-signature-style`
- `@typescript-eslint/member-delimiter-style`
- `@typescript-eslint/no-unused-vars`
> Style: enable rules of standard-with-typescript partially

- .eslintrc.js
- tests/jest-setup.ts
- Enable `@typescript-eslint/no-namespace`
- Require `namespace` word for using `CustomMatcher` in jest.
- Allow using `namespace` word only for `jest.expect.extend` .
> Style(typescript-eslint): enable no-namespace

- src/block/node/IconNode.ts
- src/block/node/StrongIconNode.ts
- tests/line/icon.test.ts
- tests/line/strongIcon.test.ts
- `[me.icon*2]` was converted to icon nodes that have same object reference.
- There should have different reference
> Fix: different (strong) icon nodes have different reference to Object

- src/block/PackedBlockComponent.ts
- To reduce cognitive complexity (#253), use `Array.prototype.reduce` and make code shorter.
> Refactor: use reduce in packBlockComponents

- src/block/BlockComponent.ts
- src/block/node/BlankNode.ts
- src/block/node/CodeNode.ts
- src/block/node/CommandLineNode.ts
- src/block/node/DecorationNode.ts
- src/block/node/ExternalLinkNode.ts
- src/block/node/FormulaNode.ts
- src/block/node/GoogleMapNode.ts
- src/block/node/HashTagNode.ts
- src/block/node/HelpfeelNode.ts
- src/block/node/IconNode.ts
- src/block/node/ImageNode.ts
- src/block/node/InternalLinkNode.ts
- src/block/node/QuoteNode.ts
- src/block/node/StrongIconNode.ts
- src/block/node/StrongImageNode.ts
- src/block/node/StrongNode.ts
- src/block/node/creator.ts
- src/parse.ts
- Use [`RegExp.prototype.exec`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec) instead of [`String.prototype.match`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match)
> Refactor: use RegExp.exec for search pattern

- src/block/node/CommandLineNode.ts
- Bug: bottom scrapbox notation was parsed to `CommandLineNode` nested with `QuoteNode`
```
> % command line node
```
- But, it is parsed to `QuoteNode` with ` % command line node` text
- To fix it, avoid parse to `CommandLineNode` on `quoted === true`
> Fix(CommandLineNode): not parse on quoted

- jest.config.js
- Use `tsconfig` instead of `tsConfig` in `jest.config.js`
- Deprecations of [ts-jest@26.4.2](https://github.com/kulshekhar/ts-jest/blob/master/CHANGELOG.md#deprecations)
- > ts-jest[config] (WARN) The option `tsConfig` is deprecated and will be removed in ts-jest 27, use `tsconfig` instead
> Chore(ts-jest): use tsconfig instead of tsConfig

- package-lock.json
- Update version of `package-lock.json` to 2.
> package-lock.json is updated to a newer format, using "lockfileVersion": 2. This format is backwards-compatible with npm CLI versions using "lockfileVersion": 1, but older npm clients will print a warning about the version mismatch.
>
> Ref. https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major
> Chore(package-lock): update lockfileVersion to 2

- src/block/node/DecorationNode.ts
- tests/line/__snapshots__/decoration.test.ts.snap
- tests/line/decoration.test.ts
-  [Regular Expression Denial-of-Service](https://owasp.org/www-community/attacks/Regular_expression_Denial_of_Service_-_ReDoS) Attack flaw has found by CodeQL
- https://github.com/progfay/scrapbox-parser/security/code-scanning/1?query=ref%3Arefs%2Fpull%2F518%2Fhead
```js
const decorationRegExp = /\[[!"#%&'()*+,-./{|}<>_~]+ (?:\[[^\]]+\]|[^\]])+\]/
`[! ${'['.repeat(30000)}z`.match(decorationRegExp) // ReDoS!!!
```
```diff
- const decorationRegExp = /\[[!"#%&'()*+,-./{|}<>_~]+ (?:\[[^\]]+\]|[^\]])+\]/
+ const decorationRegExp = /\[[!"#%&'()*+,-./{|}<>_~]+ (?:\[[^[\]]+\]|[^\]])+\]/
```
`/\[[^[\]]+\]/` RegExp fail matching for `[[` with no back tracking.
> Fix(DecorationNode): improve Inefficient regular expression

- src/block/node/StrongNode.ts
- Avoid inefficient regular expression on matching `StrongNode` .
```js
/\[\[.+?[\]]*\]\]/.exec(`${'['.repeat(30000)}z`) // ReDoS!!!
```
> Fix(StrongNode): fix Inefficient regular expression

- src/block/node/DecorationNode.ts
- Change `[,-.]` to `[,\-.]` in `decorationRegExp`
- Reported by @yuta0801 
- Ref. https://twitter.com/yuta0381/status/1368651487841198081
> refactor(DecorationNode): escape hyphen in RegExp

- src/block/node/ExternalLinkNode.ts
- tests/line/__snapshots__/link.test.ts.snap
- tests/line/link.test.ts
- Fix wrong behavior of URL text parsing
- Behavior when parsing below text:
```
ahttps://example.com/
```
```
Array [
Object {
"indent": 0,
"nodes": Array [
Object {
"raw": "a",
"text": "a",
"type": "plain",
},
Object {
"content": "",
"href": "https://example.com/",
"pathType": "absolute",
"raw": "https://example.com/",
"type": "link",
},
],
"type": "line",
},
]
```
```
Array [
Object {
"indent": 0,
"nodes": Array [
Object {
"raw": "ahttps://example.com/",
"text": "ahttps://example.com/",
"type": "plain",
},
],
"type": "line",
},
]
```
> Fix(url): match url with ahead non-space character

- package.json
- Set [`exports`](https://nodejs.org/api/packages.html#packages_exports) field for `package.json`
> Chore: set exports field for package.json

- tests/jest-setup.ts
- Follow document how to declare the custom matcher of `jest`
- ref. https://jestjs.io/docs/expect#expectextendmatchers
> fix(jest): fix typing of custom matcher `toMatchSnapshotWhenParsing`

- src/block/node/NumberListNode.ts
- src/block/node/index.ts
- src/block/node/type.ts
- tests/line/__snapshots__/numberList.test.ts.snap
- tests/line/numberList.test.ts
- number list node
- A line with `1. ` treated as `.number-list` class in Scrapbox https://scrapbox.io/scrapboxlab/番号付きリスト
- I added `NumberListNode` as a parent node of the nodes of the rest text
- e.g. `1. [* hoge]` becomes `Line > NumberListNode > DecorationNode > PlainNode`
- Should number list be new `Block` (not `Node` ) ?
- I tried to run tests ( `npm run test:update` ) but they failed on all tests as follows:
- Would you please run them instead of me?
```
FAIL  tests/line/strongIcon.test.ts
● Test suite failed to run
tests/jest-setup.ts:29:47 - error TS2554: Expected 2 arguments, but got 3.
29     return toMatchSnapshot.call(this, blocks, "toMatchSnapshotWhenParsing");
~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
> add number list node

- tsconfig.json
- The below errors ware occurred in `expect.toMatchSnapshotWhenParsing`.
- > Property `'toMatchSnapshotWhenParsing'` does not exist on type `'JestMatchers<string>'`.
- To fix this error, I added `tests/jest-setup.ts` to `compilerOptions.includes` in `tsconfig.json`.
- ref. https://github.com/testing-library/jest-dom#with-typescript
> fix(test): include extended matchers typing

- tests/.gitignore
- tsconfig.cjs.json
- tsconfig.esm.json
- tsconfig.umd.json
- Fix below errors
```console
npm ERR! error TS6059: File 'progfay/scrapbox-parser/tests/jest-setup.ts' is not under 'rootDir' 'progfay/scrapbox-parser/src'. 'rootDir' is expected to contain all source files.
npm ERR!   The file is in the program because:
npm ERR!     Matched by include pattern 'tests/jest-setup.ts' in 'tsconfig.esm.json'
npm ERR! error TS6059: File 'progfay/scrapbox-parser/tests/jest-setup.ts' is not under 'rootDir' 'progfay/scrapbox-parser/src'. 'rootDir' is expected to contain all source files.
npm ERR!   The file is in the program because:
npm ERR!     Matched by include pattern 'tests/jest-setup.ts' in 'tsconfig.cjs.json'
npm ERR! ERROR: "build:esm" exited with 2.
```
> fix(build): fix error in `npm run build`

- jest.config.mjs
- tests/codeBlock/__snapshots__/index.test.ts.snap
- tests/line/__snapshots__/blank.test.ts.snap
- tests/line/__snapshots__/bullet.test.ts.snap
- tests/line/__snapshots__/code.test.ts.snap
- tests/line/__snapshots__/commandLine.test.ts.snap
- tests/line/__snapshots__/decoration.test.ts.snap
- tests/line/__snapshots__/formula.test.ts.snap
- tests/line/__snapshots__/googleMap.test.ts.snap
- tests/line/__snapshots__/hashTag.test.ts.snap
- tests/line/__snapshots__/helpfeel.test.ts.snap
- tests/line/__snapshots__/icon.test.ts.snap
- tests/line/__snapshots__/image.test.ts.snap
- tests/line/__snapshots__/index.test.ts.snap
- tests/line/__snapshots__/link.test.ts.snap
- tests/line/__snapshots__/numberList.test.ts.snap
- tests/line/__snapshots__/plain.test.ts.snap
- tests/line/__snapshots__/quote.test.ts.snap
- tests/line/__snapshots__/strong.test.ts.snap
- tests/line/__snapshots__/strongIcon.test.ts.snap
- tests/line/__snapshots__/strongImage.test.ts.snap
- tests/line/index.test.ts
- tests/page/__snapshots__/index.test.ts.snap
- tests/table/__snapshots__/index.test.ts.snap
> Renew jest

- src/block/node/IconNode.ts
- src/block/node/StrongIconNode.ts
> untie `generateIconNodeCreator` function

- package.json
- src/block/node/NumberListNode.ts
- src/block/node/index.ts
- tests/line/__snapshots__/numberList.test.ts.snap
- tests/line/numberList.test.ts
- ref. https://github.com/progfay/scrapbox-parser/issues/1753
> fix Inconsistent parsing of number list with non-plain text

- src/block/node/ImageNode.ts
- src/block/node/StrongImageNode.ts
- tests/line/__snapshots__/image.test.ts.snap
- tests/line/__snapshots__/strongImage.test.ts.snap
- tests/line/image.test.ts
- tests/line/strongImage.test.ts
- Handle .webp URL as an Image
- Cosense supports WebP in image preview https://scrapbox.io/forum-jp/.webp%E3%81%A7%E7%B5%82%E3%82%8F%E3%82%8BURL%E3%82%82%E7%94%BB%E5%83%8F%E3%81%A8%E3%81%97%E3%81%A6%E8%A1%A8%E7%A4%BA%E3%81%97%E3%81%A6%E3%81%BB%E3%81%97%E3%81%84
> Handle .webp URL as an Image

- .github/workflows/publish.yml
- https://docs.npmjs.com/trusted-publishers
- https://github.blog/changelog/2025-07-31-npm-trusted-publishing-with-oidc-is-generally-available/
> publish package for npm with OIDC
